apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: hippo-upgrade
  namespace: databases
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.5.0-0
  postgresClusterName: hippo
  fromPostgresVersion: 14
  toPostgresVersion: 15
