apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: test
spec:
  postgresVersion: 15
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 50
        pg_hba:
          - "hostnossl all all all md5"
          - "hostssl all all all md5"
  users:
  - name: flywayadmin
    options: SUPERUSER
    password:
      type: ASCII
  - name: admin
    options: SUPERUSER
    password:
      type: ASCII
  instances:
    - name: db01
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      configuration:
        - configMap:
            name: pgbackrest-async-config
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1
