apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: manni
  namespace: databases
spec:
  postgresVersion: 15
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 50
        pg_hba:
          - "hostnossl all all all md5"
          - "hostssl all all all md5"
  users:
  - name: flyway-admin
    options: SUPERUSER
    password:
      type: ASCII
  instances:
    - name: db01
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-retention-full: '7'
        repo1-retention-diff: '48'
        repo1-retention-full-type: count
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest
        repo1-bundle: "y"
        repo1-bundle-limit: 10MiB
        repo1-bundle-size: 100MiB
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.18-0
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1
