apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: test2
spec:
  dataSource:
      postgresCluster:
        clusterName: test
        repoName: repo1
        options:
        - --type=time
        - --target="2023-09-01 17:00:00+00"
  postgresVersion: 15
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 50
        pg_hba:
          - "hostnossl all all all all"
          - "hostssl all all all all"
  instances:
    - name: db01
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      configuration:
        - configMap:
            name: pgbackrest-async-config
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
